// SPDX-License-Identifier: Apache-2.0

export default {};

//// Balance describes the `Balance` struct of Erdstall and corresponding Proofs,
//// where the `Balance` is used.
//import { Epoch } from "./epoch";
//import Values from "./value/value";
//
//// Balance is the value of funds for the account within epoch.
//export default interface Balance {
//  epoch: Epoch;
//  account: string;
//  exit: boolean;
//  values: Values;
//}
//
//// A BalanceProof is generated by the Enclave at the end of each transaction
//// phase for each account in the Erdstall system.
//export interface BalanceProof {
//  balance: Balance;
//  sig: string;
//}
//
//// MkBalance returns an initialized `Balance` struct.
//export function MkBalance(): Balance {
//  return {
//    epoch: 0n,
//    account: "",
//    value: 0n,
//    exit: false,
//  };
//}
//
//// MkBalanceProof returns an initialized `BalanceProof` struct.
//export function MkBalanceProof(): BalanceProof {
//  return {
//    balance: MkBalance(),
//    sig: "",
//  };
//}
